# Generated by Django 3.1.3 on 2020-12-11 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_ip', models.CharField(max_length=30)),
                ('origin_url', models.URLField(max_length=500)),
                ('request_tracking_code', models.CharField(max_length=30)),
                ('request_managing_code', models.CharField(max_length=30)),
                ('tracker_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 12, 2, 41, 497073))),
                ('origin_ip', models.CharField(blank=True, max_length=30)),
                ('origin_country', models.CharField(blank=True, max_length=30)),
                ('timezone', models.CharField(blank=True, max_length=30)),
                ('device_gpu', models.CharField(blank=True, max_length=30)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excavator.tracker')),
            ],
        ),
    ]
