# Generated by Django 3.1.4 on 2020-12-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='device_gpu',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='origin_country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='origin_ip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='request_api_ip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='timezone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_isp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_language',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_os',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_screensize',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_ua',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
