# Generated by Django 3.1.3 on 2020-12-12 19:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='request_managing_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='request_tracking_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracker_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
