# Generated by Django 3.1.4 on 2020-12-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excavator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='browser_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='device_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='device_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='os_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='touch_support',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
